version: '3.7'

services:

  mongodb:
    image: mongo:latest
    container_name: mongoserver
    ports:
      - 27017
    environment:
      - 'MONGO_INITDB_DATABASE=TaxiFleet'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-compose-network
    deploy:
      resources:
        limits:
          cpus: '2'
        reservations:
          cpus: '1'

  mongo-express:
    image: mongo-express
    ports:
      - 9090:8081
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongoserver'
      - 'ME_CONFIG_BASICAUTH_USERNAME=dev'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=dev_MNYM'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      - 'ME_CONFIG_MONGODB_ADMINUSERNAME=root'
      - 'ME_CONFIG_MONGODB_ADMINPASSWORD=secret'
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
volumes:
  mongodb_data: