server:
  port: 0

spring:
  application:
    name: MSTxFleet-DBS-MongoDb
  cloud:
    discovery:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092  # The address of your Kafka broker(s)
    consumer:
      auto-offset-reset: earliest  # Set the offset reset to 'earliest' or 'latest'
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Key deserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  # Value deserializer
      group-id: group_1
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: '*'

